### ISSUE TITLE
Hyperlink not working in route files

### ISSUE THREAD

**Issue by dragos** [scala-ide/scala-ide-play2#268]
```
java.lang.ClassCastException: org.scalaide.core.internal.compiler.ScalaPresentationCompiler cannot be cast to scala.tools.nsc.Global
	at org.scalaide.play2.routeeditor.hyperlink.RouteHyperlinkComputer$$anonfun$detectHyperlinks$1$$anonfun$2$$anonfun$3.apply(RouteHyperlinkComputer.scala:43)
	at org.scalaide.play2.routeeditor.hyperlink.RouteHyperlinkComputer$$anonfun$detectHyperlinks$1$$anonfun$2$$anonfun$3.apply(RouteHyperlinkComputer.scala:22)
	at scala.tools.nsc.util.InterruptReq.execute(InterruptReq.scala:26)
	at scala.tools.nsc.interactive.Global$$anonfun$pollForWork$1.apply$mcV$sp(Global.scala:457)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at scala.tools.nsc.interactive.Global.pollForWork(Global.scala:431)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:22)
```

**Comment by dragos** [comment]
This may be a binary incompatibility between my build and the Play plugin, closing it for the moment.
