### ISSUE TITLE
Unable to edit template file with 0.9.0

### ISSUE THREAD

**Issue by eximius313** [scala-ide/scala-ide-play2#275]
I have fresh install of eclipse 4.6.2 with only one plugin installed (ScalaIDE from this update site: ```http://download.scala-ide.org/sdk/lithium/e46/scala211/stable/site```)
along with: ```Play2 support in Scala IDE	0.9.0.v-2_11-201612131054-063b4e8 org.scala-ide.play2.feature.feature.group```

When I open any template file the HTML syntax is not colored and if I modify the file - changes are not shown (editor "freezes")

**Comment by scalastic** [comment]
Same exasperating problem ! 
When entering a simple new line in a view template, everything goes wrong (Cf. logs below)

Clean 4.6.2 eclipse with latest and up-to-date `Scala IDE for Eclipse 4.5.0.v-2_11-201612131030-02830a6` and `Play2 support in Scala IDE	0.9.0.v-2_11-201612131054-063b4e8`.

Eclipse log :

```
!SESSION 2017-03-16 12:23:14.124 -----------------------------------------------
eclipse.buildId=4.5.0-vfinal-2016-12-13T10:59:29Z-Typesafe
java.version=1.8.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=fr_FR
Framework arguments:  -keyring /Users/jeanjerome/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/jeanjerome/.eclipse_keyring

!ENTRY org.eclipse.core.resources 2 10035 2017-03-16 12:23:16.155
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.core.net 1 0 2017-03-16 12:23:20.108
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.scala-ide.sdt.core 2 0 2017-03-16 12:23:23.250
!MESSAGE Preference scala.compiler.sourceLevel was uninitialized for finapp-web, setting default to 2.11.

!ENTRY org.scala-ide.sdt.core 2 0 2017-03-16 12:23:23.265
!MESSAGE Preference scala.compiler.installation was uninitialized for finapp-web, setting default to 2.11.

!ENTRY org.eclipse.ui 4 0 2017-03-16 12:25:05.313
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jface.text.DefaultPositionUpdater.update(DefaultPositionUpdater.java:209)
	at org.eclipse.jface.text.AbstractDocument.updatePositions(AbstractDocument.java:1157)
	at org.eclipse.jface.text.AbstractDocument.updateDocumentStructures(AbstractDocument.java:682)
	at org.eclipse.jface.text.projection.ProjectionDocument.updateDocumentStructures(ProjectionDocument.java:775)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:767)
	at org.eclipse.jface.text.projection.ProjectionDocument.fireDocumentChanged(ProjectionDocument.java:770)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1101)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1119)
	at org.eclipse.jface.text.projection.ProjectionDocument.replace(ProjectionDocument.java:625)
	at org.eclipse.jface.text.DefaultDocumentAdapter.replaceTextRange(DefaultDocumentAdapter.java:233)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7374)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8225)
	at org.eclipse.swt.custom.StyledText.doContent(StyledText.java:2530)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6018)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6049)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5733)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1534)
	at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:515)
	at org.eclipse.swt.widgets.Control.doCommandBySelector(Control.java:1090)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5825)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:68)
	at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:610)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5735)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:227)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2140)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2402)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5797)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5226)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5375)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3703)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```

**Comment by lagerspetz** [comment]
Hi, I have the same issue with Scala IDE 4.5.0 with all of my Play projects. This has been reported by other users also in Scala IDE: https://groups.google.com/forum/#!searchin/scala-ide-user/template$20editor%7Csort:relevance/scala-ide-user/q9zkW2lA2e4/TgrEsY-pDwAJ

The funny thing is that the "Template Editor" works fine for me, but "New Template Editor" (currently the default) does not work.

**Comment by karateboy** [comment]
I also have the same issue with 4.5. I thought this is due to the template contains utf-8 Chinese character. This issue has been there for a while. In the mean time, I still stick to IDE 4.4

**Comment by wpopielarski** [comment]
right now Scala IDE in 4.6.0 is not supporting Play2 because problems with
incompatibilities with scala 2.12.1. Just as remainder Scala IDE 4,5.0
supports Play 2.3 and 2.4 which are compliant with scala 2.11.x. Currently
we are thinking to support 2.5 and potentially 2.6 but work is not started
yet. Sorry for potential inconvenience,

2017-04-25 9:02 GMT+02:00 Aragorn Huang <notifications@github.com>:

**Comment by eximius313** [comment]
well, since 2.4 is two years old now (May 26 2015) it would be great if you support 2.5 and 2.6
I think we're all eagerly waiting for that

**Comment by karateboy** [comment]
Thank for the information. I can manually open play template by "Template Editor" without any problem. Does you have any plan to fix it? Or how can I set the default editor back to "Template Editor"?

**Comment by lagerspetz** [comment]
@wpopielarski  I experienced this problem with out of the box http://scala-ide.org/ 4.5.0 with Play 2.5.14. I have not tried with 4.6.0 yet.

**Comment by wpopielarski** [comment]
4.5.0 supports Play 2.3 and 2.4. Actually it is connected with twirl
versions accordingly 1.0.4 and 1.1.1. It needs to be upgraded too.

2017-05-02 10:09 GMT+02:00 Eemil Lagerspetz <notifications@github.com>:

**Comment by karateboy** [comment]
@wpopielarski How can I upgrade the editor?

**Comment by wpopielarski** [comment]
now we are in releasing of 4.6.0 process. We plan RC2 this Thursday and
week later if no blocking bugs will be found, final. So I think the prudent
and safe estimate for 2.5 and potentially 2.6 will be added around end of
May.

2017-05-02 10:45 GMT+02:00 Aragorn Huang <notifications@github.com>:

**Comment by eximius313** [comment]
Fabulous! Are you testing it also against Eclipse Oxygen (4.7)?

**Comment by lagerspetz** [comment]
@eximius313  Looks like plugin-profiles will need to be updated with e47 before this is possible...

**Comment by lagerspetz** [comment]
I'm getting the same issue with "new template editor" with a Play 2.6.0-M5 project using the new 0.10.0 version.
I built it from https://github.com/wpopielarski/scala-ide-play2/tree/0.10.0 using the build args: 
`mvn -Peclipse-neon -Pscala-ide-dev -Pscala-2.12.x clean verify`.
I then installed from the local update site that the build creates on a clean Scala-IDE 4.6.0 release. I also had to modify plugin-profiles to set the scala-version to 2.12.0 for the 2.12.x profile for it to build properly.

**Comment by wpopielarski** [comment]
I'm working on it. I think the problem is nailed but needs implementation.
Hope today there will be some solution.

2017-05-20 16:41 GMT+02:00 Eemil Lagerspetz <notifications@github.com>:

**Comment by eximius313** [comment]
Great!
For the record: Play is in 2.6 RC1 now, so it's quite stable

**Comment by wpopielarski** [comment]
I expect that Release Candidate will be available in end of week.

2017-05-24 2:58 GMT+02:00 Kamil <notifications@github.com>:

**Comment by lagerspetz** [comment]
Hi, I can confirm that the problem does not present on Scala IDE 4.6.1-RC1 with my Play 2.5.14 project. I downloaded a new copy of RC1, opened it with a new workspace, imported my project (created with activator eclipse), and opened scala.html template files, and everything worked fine.

**Comment by lagerspetz** [comment]
New Template Editor verified to work well also on the laptop. THANK YOU!

**Comment by wpopielarski** [comment]
so today I start releasing of 4.6.1 final, thanks for your help

2017-06-08 12:26 GMT+02:00 Eemil Lagerspetz <notifications@github.com>:

**Comment by eximius313** [comment]
Has anybody tested it with Eclipse Oxygen and Play 2.6 yet?

**Comment by lagerspetz** [comment]
@eximius313 can you give some instructions how to get Eclipse Oxygen with Java? I found this page: http://download.eclipse.org/eclipse/downloads/ with 4.7RC4, but would need to combine things myself for the standard Eclipse for Java. Is there a better download link somewhere?

Also, is this issue solved for you for Scala-IDE 4.6.1? Maybe you can open a new Issue if it doesn't work with Eclipse Oxygen.

**Comment by lagerspetz** [comment]
With the Oxygen version from the Installer, combined with this update site:  http://download.scala-ide.org/sdk/lithium/e46/scala212/dev/site , the ( new ) template editor works well for me with a Play 2.5.14 project.
