### ISSUE TITLE
Could not create content describer for scala.tools.eclipse.scalaClass. Content type has been disabled.

### ISSUE THREAD

**Issue by eximius313** [scala-ide/scala-ide-play2#281]
Eclipse displays this error:
```
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:204)
	at scala.tools.scalap.Classfile.<init>(Classfile.scala:17)
	at org.scalaide.core.internal.jdt.model.ScalaClassFileDescriber$.isScala(ScalaClassFileDescriber.scala:16)
	at org.scalaide.core.internal.jdt.model.ScalaClassFileDescriber.describe(ScalaClassFileDescriber.scala:38)
	at org.eclipse.core.internal.content.ContentTypeCatalog.describe(ContentTypeCatalog.java:226)
	at org.eclipse.core.internal.content.ContentTypeCatalog.collectMatchingByContents(ContentTypeCatalog.java:197)
	at org.eclipse.core.internal.content.ContentTypeCatalog.internalFindContentTypesFor(ContentTypeCatalog.java:411)
	at org.eclipse.core.internal.content.ContentTypeCatalog.internalFindContentTypesFor(ContentTypeCatalog.java:458)
	at org.eclipse.core.internal.content.ContentTypeCatalog.getDescriptionFor(ContentTypeCatalog.java:354)
	at org.eclipse.core.internal.content.ContentTypeCatalog.getDescriptionFor(ContentTypeCatalog.java:368)
	at org.eclipse.core.internal.content.ContentTypeMatcher.getDescriptionFor(ContentTypeMatcher.java:76)
	at org.eclipse.core.internal.resources.ContentDescriptionManager.readDescription(ContentDescriptionManager.java:453)
	at org.eclipse.core.internal.resources.ContentDescriptionManager.getDescriptionFor(ContentDescriptionManager.java:363)
	at org.eclipse.core.internal.resources.File.getContentDescription(File.java:263)
	at org.eclipse.wst.validation.internal.ValidatorMetaData.isApplicableTo(ValidatorMetaData.java:324)
	at org.eclipse.wst.validation.internal.ValidatorMetaData.isApplicableTo(ValidatorMetaData.java:302)
	at org.eclipse.wst.validation.internal.ValidatorMetaData.isApplicableTo(ValidatorMetaData.java:287)
	at org.eclipse.wst.validation.Validator$V1.shouldValidate(Validator.java:739)
	at org.eclipse.wst.validation.Validator.shouldValidate(Validator.java:320)
	at org.eclipse.wst.validation.Friend.shouldValidate(Friend.java:50)
	at org.eclipse.wst.validation.internal.ValManager.accept(ValManager.java:800)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:669)
	at org.eclipse.wst.validation.internal.ValBuilderJob$Visitor.visit(ValBuilderJob.java:299)
	at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:120)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at org.eclipse.wst.validation.internal.ValBuilderJob.fullBuild(ValBuilderJob.java:219)
	at org.eclipse.wst.validation.internal.ValBuilderJob.run(ValBuilderJob.java:178)
	at org.eclipse.wst.validation.internal.ValBuilderJob.runInWorkspace(ValBuilderJob.java:126)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by wpopielarski** [comment]
would be nice to see reproduction steps. thanks in advance

**Comment by eximius313** [comment]
Fresh instalation of Eclipse Oxygen 1a: I just opened my project.

**Comment by wpopielarski** [comment]
same problem with Play on 4.7.0 final?

2017-10-14 15:13 GMT+02:00 Kamil <notifications@github.com>:

**Comment by wpopielarski** [comment]
btw problems with scalap mean problems with incompatibility of java
bytecode. so maybe it is good enough to clean build project assuring first
that it is working with java 8 not 9 or 7?

2017-10-14 19:35 GMT+02:00 Wieslaw Popielarski <wpopielarski@gmail.com>:

**Comment by eximius313** [comment]
I've noticed that this happens when I have Scala IDE installed and I'm switching workspace from the one containing Play project to the one containing SpringBoot project

**Comment by wpopielarski** [comment]
ok, but are these projects using same java version to compile?

2017-10-19 12:40 GMT+02:00 Kamil <notifications@github.com>:

**Comment by wpopielarski** [comment]
would be nice if you could send me the minimal projects to reproduce it.

2017-10-20 8:51 GMT+02:00 Wieslaw Popielarski <wpopielarski@gmail.com>:

**Comment by Heraptor** [comment]
This problem is troubling now, just the same,
!ENTRY org.eclipse.core.contenttype 4 0 2017-10-31 15:38:29.020
!MESSAGE Could not create content describer for scala.tools.eclipse.scalaClass. Content type has been disabled.
!STACK 0
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:204)
	at scala.tools.scalap.Classfile.<init>(Classfile.scala:17)
	at org.scalaide.core.internal.jdt.model.ScalaClassFileDescriber$.isScala(ScalaClassFileDescriber.scala:16)
	at org.scalaide.core.internal.jdt.model.ScalaClassFileDescriber.describe(ScalaClassFileDescriber.scala:38)

**Comment by wpopielarski** [comment]
https://github.com/scala-ide/scala-ide/pull/1184
